/**
 * sync-locales.mjs — single source of truth → generated bundles.
 *
 * Sources:  shared/locales/{ext,us,site}/{en,zh-CN,zh-TW}.json
 * Outputs:
 *   - extension/i18n-bundle.js   (ext namespace + createI18n runtime)
 *   - website/i18n.js             (site namespace + createI18n runtime)
 *   - userscript languageResources block (us namespace, inlined between markers)
 *
 * Validates that every locale exposes the same keys as `en` for its namespace.
 * Run via `npm run i18n:sync`.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(__dirname, "..")
const localesDir = path.join(root, "shared", "locales")
const runtimePath = path.join(root, "shared", "i18n.js")

const NAMESPACES = ["ext", "us", "site"]
const LOCALES = ["en", "zh-CN", "zh-TW"]

function readJson(p) {
    return JSON.parse(readFileSync(p, "utf8"))
}

function loadNamespace(ns) {
    const packs = {}
    for (const loc of LOCALES) {
        const file = path.join(localesDir, ns, `${loc}.json`)
        if (!existsSync(file)) {
            throw new Error(`Missing locale file: ${file}`)
        }
        packs[loc] = readJson(file)
    }
    return packs
}

function validate(ns, packs) {
    const enKeys = Object.keys(packs.en).sort()
    const errors = []
    for (const loc of LOCALES) {
        if (loc === "en") continue
        const keys = Object.keys(packs[loc]).sort()
        const missing = enKeys.filter((k) => !keys.includes(k))
        const extra = keys.filter((k) => !enKeys.includes(k))
        if (missing.length) {
            errors.push(`${ns}/${loc}: missing ${missing.join(", ")}`)
        }
        if (extra.length) {
            errors.push(`${ns}/${loc}: unexpected ${extra.join(", ")}`)
        }
    }
    if (errors.length) {
        throw new Error("Locale key mismatch:\n  " + errors.join("\n  "))
    }
}

function serializeLocales(packs) {
    // Stable, readable JS object literal (not JSON) so bundles stay diff-friendly.
    const parts = []
    for (const loc of LOCALES) {
        const entries = Object.keys(packs[loc])
            .sort()
            .map((k) => {
                const v = JSON.stringify(packs[loc][k])
                return `        ${JSON.stringify(k)}: ${v}`
            })
        parts.push(`    ${JSON.stringify(loc)}: {\n${entries.join(",\n")}\n    }`)
    }
    return `{\n${parts.join(",\n")}\n}`
}

function header() {
    return (
        "/**\n" +
        " * AUTO-GENERATED by scripts/sync-locales.mjs — do not edit by hand.\n" +
        " * Source: shared/locales/* + shared/i18n.js. Run `npm run i18n:sync`.\n" +
        " */\n"
    )
}

function buildExtensionBundle(extPacks) {
    const runtime = readFileSync(runtimePath, "utf8")
    const locales = `var I18nLocales = ${serializeLocales(extPacks)};\n`
    const boot =
        "\n;(function () {\n" +
        '    "use strict"\n' +
        "    window.I18n = createI18n(I18nLocales)\n" +
        "})()\n"
    return header() + runtime + "\n" + locales + boot
}

function buildWebsiteBundle(sitePacks) {
    const runtime = readFileSync(runtimePath, "utf8")
    const locales = `var I18nLocales = ${serializeLocales(sitePacks)};\n`
    const boot =
        "\n;(function () {\n" +
        '    "use strict"\n' +
        "    var i18n = createI18n(I18nLocales)\n" +
        "    window.i18n = i18n\n" +
        "    // Back-compat: script.js reads translations[lang][key] directly.\n" +
        "    window.translations = I18nLocales\n" +
        "})()\n"
    return header() + runtime + "\n" + locales + boot
}

function buildUserscriptBlock(usPacks) {
    // The userscript keeps its own getText/getEffectiveLanguage logic; only the
    // data object is generated. Keys are emitted unsorted (insertion order) to
    // match the original hand-written layout and minimize diff noise.
    const parts = []
    for (const loc of LOCALES) {
        const entries = Object.keys(usPacks[loc]).map((k) => {
            const v = JSON.stringify(usPacks[loc][k])
            return `            ${JSON.stringify(k)}: ${v}`
        })
        parts.push(
            `        ${JSON.stringify(loc)}: {\n${entries.join(",\n")}\n        }`
        )
    }
    return `    const languageResources = {\n${parts.join(",\n")}\n    }`
}

function patchUserscript(usPacks) {
    const file = path.join(root, "userscript", "OpenInNewTab.user.js")
    const src = readFileSync(file, "utf8")
    const startMarker = "// __I18N_START__"
    const endMarker = "// __I18N_END__"
    const startIdx = src.indexOf(startMarker)
    const endIdx = src.indexOf(endMarker)
    if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
        throw new Error(
            `Userscript i18n markers not found. Expected ${startMarker} / ${endMarker} around the languageResources block.`
        )
    }
    const block = buildUserscriptBlock(usPacks)
    const next =
        src.slice(0, startIdx + startMarker.length) +
        "\n" +
        block +
        "\n" +
        src.slice(endIdx)
    writeFileSync(file, next, "utf8")
}

function main() {
    const packsByNs = {}
    for (const ns of NAMESPACES) {
        packsByNs[ns] = loadNamespace(ns)
        validate(ns, packsByNs[ns])
    }

    const extBundle = buildExtensionBundle(packsByNs.ext)
    writeFileSync(path.join(root, "extension", "i18n-bundle.js"), extBundle, "utf8")

    const siteBundle = buildWebsiteBundle(packsByNs.site)
    writeFileSync(path.join(root, "website", "i18n.js"), siteBundle, "utf8")

    patchUserscript(packsByNs.us)

    console.log(
        "sync-locales: wrote extension/i18n-bundle.js, website/i18n.js, patched userscript languageResources"
    )
}

main()
