/**
 * AUTO-GENERATED by scripts/sync-locales.mjs — do not edit by hand.
 * Source: shared/locales/* + shared/i18n.js. Run `npm run i18n:sync`.
 */
/* exported createI18n */
/**
 * Shared i18n runtime. `scripts/sync-locales.mjs` concatenates this after
 * `I18nLocales`. Consumers call `createI18n(I18nLocales)`.
 *
 * Locale ids are BCP-47: en, zh-CN, zh-TW.
 * Legacy stored "zh" canonicalizes to zh-CN.
 * zh-HK / zh-MO / zh-Hant* map to zh-TW; other zh* map to zh-CN.
 */
function createI18n(locales) {
    "use strict"

    const DEFAULT_LOCALE = "en"
    const SUPPORTED_LOCALES = Object.freeze(["en", "zh-CN", "zh-TW"])
    const LOCALE_LABELS = Object.freeze([
        { id: "en", label: "English" },
        { id: "zh-CN", label: "简体中文" },
        { id: "zh-TW", label: "繁體中文" },
    ])
    const catalog = locales && typeof locales === "object" ? locales : {}

    function normalizeLocale(input) {
        if (input == null) {
            return DEFAULT_LOCALE
        }
        const raw = String(input).trim().replace(/_/g, "-")
        if (!raw || raw === "auto") {
            return DEFAULT_LOCALE
        }
        if (SUPPORTED_LOCALES.indexOf(raw) !== -1) {
            return raw
        }
        const lower = raw.toLowerCase()
        if (
            lower === "zh-tw" ||
            lower === "zh-hk" ||
            lower === "zh-mo" ||
            lower === "zh-hant" ||
            lower.indexOf("zh-hant") === 0 ||
            lower.indexOf("zh-tw") === 0 ||
            lower.indexOf("zh-hk") === 0 ||
            lower.indexOf("zh-mo") === 0
        ) {
            return "zh-TW"
        }
        if (lower.indexOf("zh") === 0) {
            return "zh-CN"
        }
        return DEFAULT_LOCALE
    }

    function detectLocale(hint) {
        const source =
            hint ||
            (typeof navigator !== "undefined" &&
                (navigator.language || navigator.userLanguage)) ||
            DEFAULT_LOCALE
        return normalizeLocale(source)
    }

    function resolveStoredLocale(stored) {
        if (stored == null || stored === "" || stored === "auto") {
            return detectLocale()
        }
        return normalizeLocale(stored)
    }

    function canonicalizeStoredLocale(stored, options) {
        const allowAuto = Boolean(options && options.allowAuto)
        if (stored == null || stored === "") {
            return allowAuto ? "auto" : detectLocale()
        }
        if (stored === "auto") {
            return allowAuto ? "auto" : detectLocale()
        }
        return normalizeLocale(stored)
    }

    function interpolate(text, params) {
        if (!params) {
            return text
        }
        return String(text).replace(/\{(\w+)\}/g, function (_, name) {
            return params[name] == null ? "{" + name + "}" : String(params[name])
        })
    }

    function getText(key, locale, params) {
        const resolved = normalizeLocale(locale)
        const pack = catalog[resolved] || catalog[DEFAULT_LOCALE] || {}
        const fallback = catalog[DEFAULT_LOCALE] || {}
        const text = pack[key] || fallback[key] || key
        return interpolate(text, params)
    }

    function fillLanguageSelect(selectEl, current) {
        if (!selectEl) {
            return
        }
        const resolved = normalizeLocale(current)
        selectEl.innerHTML = LOCALE_LABELS.map(function (item) {
            return (
                '<option value="' + item.id + '">' + item.label + "</option>"
            )
        }).join("")
        selectEl.value = resolved
    }

    function isSupportedLocale(value) {
        return SUPPORTED_LOCALES.indexOf(value) !== -1
    }

    function greasyForkLangPrefix(locale) {
        const resolved = normalizeLocale(locale)
        if (resolved === "zh-CN" || resolved === "zh-TW") {
            return resolved
        }
        return "en"
    }

    return {
        DEFAULT_LOCALE: DEFAULT_LOCALE,
        SUPPORTED_LOCALES: SUPPORTED_LOCALES,
        LOCALE_LABELS: LOCALE_LABELS,
        locales: catalog,
        normalizeLocale: normalizeLocale,
        detectLocale: detectLocale,
        resolveStoredLocale: resolveStoredLocale,
        canonicalizeStoredLocale: canonicalizeStoredLocale,
        interpolate: interpolate,
        getText: getText,
        htmlLang: normalizeLocale,
        greasyForkLangPrefix: greasyForkLangPrefix,
        fillLanguageSelect: fillLanguageSelect,
        isSupportedLocale: isSupportedLocale,
    }
}

var I18nLocales = {
    "en": {
        "badgeDarkMode": "Dark Mode",
        "badgeI18n": "i18n Support",
        "badgeLightweight": "Lightweight",
        "badgeRecommended": "Recommended",
        "badgeSecure": "Secure",
        "btnCopied": "Copied!",
        "btnCopyFailed": "Failed",
        "btnCopyLink": "Copy Link",
        "btnGetStarted": "Get Started",
        "btnInstallExtension": "Install Extension →",
        "btnInstallNow": "Install Now →",
        "btnInstallUserscript": "Install Userscript →",
        "btnViewDocs": "View Documentation",
        "btnViewGithub": "View on GitHub",
        "comparisonDarkMode": "Dark Mode",
        "comparisonDistGithub": "GitHub",
        "comparisonDistWebStore": "Chrome Web Store",
        "comparisonDistribution": "Distribution",
        "comparisonExtension": "Extension",
        "comparisonFeature": "Feature",
        "comparisonI18n": "Internationalization",
        "comparisonInstallManual": "Manual Script",
        "comparisonInstallOneClick": "One-Click",
        "comparisonInstallation": "Installation",
        "comparisonLinkManagement": "Link Management",
        "comparisonTitle": "Feature Comparison",
        "comparisonUIMenu": "Menu Commands",
        "comparisonUIPopup": "Popup Interface",
        "comparisonUIType": "UI Type",
        "comparisonUpdates": "Updates",
        "comparisonUpdatesAuto": "Automatic",
        "comparisonUpdatesManual": "Manual",
        "comparisonUserscript": "Userscript",
        "comparisonWhitelist": "Whitelist Control",
        "ctaDesc": "Choose your preferred version and start managing your links smarter today.",
        "ctaTitle": "Ready to Get Started?",
        "featureDarkModeDesc": "Automatically adapts to system dark/light mode preferences with smooth transitions.",
        "featureDarkModeTitle": "Dark Mode",
        "featureDynamicDesc": "Handles both existing and dynamically added links using MutationObserver for real-time updates. Each link opens in new tab.",
        "featureDynamicTitle": "Dynamic Content",
        "featureI18nDesc": "Auto language detection (English / 简体中文 / 繁體中文) based on browser settings.",
        "featureI18nTitle": "Internationalization",
        "featureSecurityDesc": "Adds rel=\"noopener noreferrer\" to prevent security issues. Your browsing stays safe.",
        "featureSecurityTitle": "Security First",
        "featureStorageDesc": "Your whitelist preferences are saved and synced across devices automatically.",
        "featureStorageTitle": "Persistent Storage",
        "featureWhitelistDesc": "Only applies to specified domains for better control and performance. You decide which sites to enhance.",
        "featureWhitelistTitle": "Whitelist Mode",
        "featuresSubtitle": "Everything you need for smart link management",
        "featuresTitle": "Powerful Features",
        "footerCopyright": "© 2025 Open In New Tab. Released under MIT License.",
        "footerDesc": "Smart link management with whitelist control. Available as extension and userscript.",
        "footerExtensionDocs": "Extension Docs",
        "footerGithubRepo": "GitHub Repository",
        "footerLicense": "MIT License",
        "footerMadeWith": "Made with ❤️ by",
        "footerMainDocs": "Main Documentation",
        "footerPrivacyPolicy": "Privacy Policy",
        "footerQuickLinks": "Quick Links",
        "footerReleaseVersion": "Release v{version}",
        "footerReportIssues": "Report Issues",
        "footerResources": "Resources",
        "footerTitle": "Open In New Tab",
        "footerUserscriptDocs": "Userscript Docs",
        "heroSubtitle": "Force all links to open in new tab with intelligent whitelist control.",
        "heroSubtitle2": "Available as Chrome extension and Tampermonkey userscript for opening each link in new tab.",
        "heroTitle": "Smart Link Management",
        "heroTitleHighlight": "Your Way",
        "installExtensionNote": "Tip:",
        "installExtensionNoteText": "The extension is now available for one-click installation from the Chrome Web Store.",
        "installExtensionStep1Desc": "Go to the official Chrome Web Store page.",
        "installExtensionStep1Title": "Visit Web Store",
        "installExtensionStep2Desc": "Click 'Add to Chrome' to install instantly.",
        "installExtensionStep2Title": "Add to Chrome",
        "installExtensionStep3Desc": "Click the extension icon to manage your whitelist.",
        "installExtensionStep3Title": "Start Using",
        "installExtensionStep4Desc": "",
        "installExtensionStep4Title": "",
        "installTitle": "Quick Installation",
        "installUserscriptAlternative": "Alternative: Manual Installation",
        "installUserscriptBtnDirect": "Direct Install",
        "installUserscriptBtnGreasyFork": "Install from Greasy Fork",
        "installUserscriptManualDesc": "If you prefer manual installation, download the script from GitHub and install it manually in Tampermonkey.",
        "installUserscriptStep1Desc1": "Install the",
        "installUserscriptStep1Desc2": "browser extension from your browser's extension store.",
        "installUserscriptStep1Title": "Install Tampermonkey",
        "installUserscriptStep2Desc": "Click the install button below to go to Greasy Fork and install the script with one click.",
        "installUserscriptStep2Title": "One-Click Install",
        "installUserscriptStep3Desc": "Navigate to any website, open Tampermonkey menu to add domains to whitelist.",
        "installUserscriptStep3Title": "Start Using",
        "navFeatures": "Features",
        "navHome": "Home",
        "navInstall": "Installation",
        "navVersions": "Versions",
        "privacyBackHome": "Back to Home",
        "privacyChangesDesc": "We may update this privacy policy from time to time. Changes will be posted on this page.",
        "privacyChangesTitle": "Changes to This Policy",
        "privacyContactDesc": "For questions about this privacy policy, please visit:",
        "privacyContactTitle": "Contact",
        "privacyDataCollectionDesc": "Open In New Tab does not collect, store, or transmit any personal data to external servers.",
        "privacyDataCollectionTitle": "Data Collection",
        "privacyLastUpdated": "Last updated:",
        "privacyLastUpdatedDate": "August 24, 2026",
        "privacyPermActiveTab": "Used to detect current tab's domain for quick-add feature",
        "privacyPermHost": "Matches *://*/* for static content scripts. They load on matching pages, but modify links and intercept clicks only on whitelisted domains.",
        "privacyPermStorage": "Used to save the five fields listed above via chrome.storage.sync",
        "privacyPermissionsTitle": "Permissions",
        "privacyPolicyTitle": "Privacy Policy for Open In New Tab",
        "privacySyncStorageDesc1": "The extension uses Chrome sync storage (chrome.storage.sync) to save these five fields:",
        "privacySyncStorageDesc2": "This data stays in Chrome's storage. When you're signed in to Chrome, Chrome may synchronize it across your signed-in browsers. We do not have access to this data.",
        "privacySyncStorageItem1": "userWhitelist — your whitelist of domain names",
        "privacySyncStorageItem2": "openInBackground — whether new tabs open in the background",
        "privacySyncStorageItem3": "userTheme — your theme preference (light, dark, or auto)",
        "privacySyncStorageItem4": "userLanguage — your language preference",
        "privacySyncStorageItem5": "updateNoticeEnabled — whether to show update notices after extension updates",
        "privacySyncStorageTitle": "Chrome Sync Storage",
        "privacyThirdPartyDesc": "This extension does not use any third-party services, analytics, or tracking tools.",
        "privacyThirdPartyTitle": "Third-Party Services",
        "screenshotCaptionDark": "Chrome Extension - Dark Mode",
        "screenshotCaptionLight": "Chrome Extension - Light Mode",
        "screenshotCaptionUserscript": "Userscript - Modal Interface",
        "screenshotDarkMode": "Dark mode enabled",
        "screenshotExtensionPopup": "Extension Popup",
        "screenshotModalInterface": "Userscript modal interface",
        "screenshotQuickAdd": "Quick add current domain",
        "screenshotWhitelistManager": "Whitelist Manager",
        "screenshotsSubtitle": "Modern UI with dark mode support",
        "screenshotsTitle": "Beautiful Interface",
        "tabExtension": "Extension",
        "tabUserscript": "Userscript",
        "versionExtensionBestFor": "Best for:",
        "versionExtensionBestForText": "Production use, end users, Web Store distribution",
        "versionExtensionDesc": "Native Chrome extension with better performance and seamless browser integration.",
        "versionExtensionFeature1": "Modern popup interface",
        "versionExtensionFeature2": "Quick add current domain",
        "versionExtensionFeature3": "chrome.storage sync",
        "versionExtensionFeature4": "Auto-updates (Web Store)",
        "versionExtensionFeature5": "Better performance",
        "versionExtensionFeatures": "Features:",
        "versionExtensionTitle": "Chrome Extension",
        "versionUserscriptBestFor": "Best for:",
        "versionUserscriptBestForText": "Developers, power users, quick testing",
        "versionUserscriptDesc": "Perfect for quick testing, development, or users who prefer Tampermonkey/Greasemonkey.",
        "versionUserscriptFeature1": "Menu-based management",
        "versionUserscriptFeature2": "GM_* APIs for storage",
        "versionUserscriptFeature3": "Modal interface",
        "versionUserscriptFeature4": "Cross-browser support",
        "versionUserscriptFeature5": "Easy to customize",
        "versionUserscriptFeatures": "Features:",
        "versionUserscriptTitle": "Userscript Version",
        "versionsSubtitle": "Two implementations, same great features",
        "versionsTitle": "Choose Your Version"
    },
    "zh-CN": {
        "badgeDarkMode": "深色模式",
        "badgeI18n": "国际化支持",
        "badgeLightweight": "轻量级",
        "badgeRecommended": "推荐",
        "badgeSecure": "安全可靠",
        "btnCopied": "已复制！",
        "btnCopyFailed": "复制失败",
        "btnCopyLink": "复制链接",
        "btnGetStarted": "立即开始",
        "btnInstallExtension": "安装扩展 →",
        "btnInstallNow": "立即安装 →",
        "btnInstallUserscript": "安装用户脚本 →",
        "btnViewDocs": "查看文档",
        "btnViewGithub": "查看仓库",
        "comparisonDarkMode": "深色模式",
        "comparisonDistGithub": "GitHub",
        "comparisonDistWebStore": "Chrome 应用商店",
        "comparisonDistribution": "分发方式",
        "comparisonExtension": "扩展",
        "comparisonFeature": "功能",
        "comparisonI18n": "国际化",
        "comparisonInstallManual": "手动脚本",
        "comparisonInstallOneClick": "一键安装",
        "comparisonInstallation": "安装方式",
        "comparisonLinkManagement": "链接管理",
        "comparisonTitle": "功能对比",
        "comparisonUIMenu": "菜单命令",
        "comparisonUIPopup": "弹出界面",
        "comparisonUIType": "界面类型",
        "comparisonUpdates": "更新",
        "comparisonUpdatesAuto": "自动",
        "comparisonUpdatesManual": "手动",
        "comparisonUserscript": "用户脚本",
        "comparisonWhitelist": "白名单控制",
        "ctaDesc": "选择你偏好的版本，立即开始更智能地管理你的链接。",
        "ctaTitle": "准备好开始了吗？",
        "featureDarkModeDesc": "自动适配系统深色/浅色模式偏好，并提供平滑过渡动画。",
        "featureDarkModeTitle": "深色模式",
        "featureDynamicDesc": "使用 MutationObserver 处理现有和动态添加的链接，实现实时更新。",
        "featureDynamicTitle": "动态内容",
        "featureI18nDesc": "基于浏览器设置自动检测语言（English / 简体中文 / 繁體中文）。",
        "featureI18nTitle": "国际化",
        "featureSecurityDesc": "自动添加 rel=\"noopener noreferrer\" 属性以防止安全问题。让你的浏览更安全。",
        "featureSecurityTitle": "安全优先",
        "featureStorageDesc": "你的白名单偏好设置会自动保存并跨设备同步。",
        "featureStorageTitle": "持久化存储",
        "featureWhitelistDesc": "仅应用于指定域名，实现更好的控制和性能。由你决定要增强哪些网站。",
        "featureWhitelistTitle": "白名单模式",
        "featuresSubtitle": "智能链接管理所需的一切功能",
        "featuresTitle": "强大功能",
        "footerCopyright": "© 2025 Open In New Tab. 基于 MIT 许可证发布。",
        "footerDesc": "智能链接管理与白名单控制。提供扩展和用户脚本两个版本。",
        "footerExtensionDocs": "扩展文档",
        "footerGithubRepo": "GitHub 仓库",
        "footerLicense": "MIT 许可证",
        "footerMadeWith": "用 ❤️ 制作 by",
        "footerMainDocs": "主文档",
        "footerPrivacyPolicy": "隐私政策",
        "footerQuickLinks": "快速链接",
        "footerReleaseVersion": "当前发布版本 v{version}",
        "footerReportIssues": "报告问题",
        "footerResources": "资源",
        "footerTitle": "Open In New Tab",
        "footerUserscriptDocs": "用户脚本文档",
        "heroSubtitle": "通过智能白名单控制，强制每个链接在新标签页打开。",
        "heroSubtitle2": "提供 Chrome 扩展和 Tampermonkey 用户脚本两个版本。",
        "heroTitle": "智能链接管理",
        "heroTitleHighlight": "随心所控",
        "installExtensionNote": "提示：",
        "installExtensionNoteText": "扩展程序现已正式上线 Chrome 应用商店，推荐使用一键安装。",
        "installExtensionStep1Desc": "前往 Chrome 应用商店官方页面。",
        "installExtensionStep1Title": "访问应用商店",
        "installExtensionStep2Desc": "点击\"添加至 Chrome\"即可完成一键安装。",
        "installExtensionStep2Title": "添加至 Chrome",
        "installExtensionStep3Desc": "点击浏览器右上角的扩展图标即可管理白名单。",
        "installExtensionStep3Title": "开始使用",
        "installExtensionStep4Desc": "",
        "installExtensionStep4Title": "",
        "installTitle": "快速安装",
        "installUserscriptAlternative": "备选方案：手动安装",
        "installUserscriptBtnDirect": "直接安装",
        "installUserscriptBtnGreasyFork": "从 Greasy Fork 安装",
        "installUserscriptManualDesc": "如果您偏好手动安装，可以从 GitHub 下载脚本并在 Tampermonkey 中手动安装。",
        "installUserscriptStep1Desc1": "安装",
        "installUserscriptStep1Desc2": "浏览器扩展。",
        "installUserscriptStep1Title": "安装 Tampermonkey",
        "installUserscriptStep2Desc": "点击下方安装按钮前往 Greasy Fork，一键安装脚本。",
        "installUserscriptStep2Title": "一键安装",
        "installUserscriptStep3Desc": "访问任意网站，打开 Tampermonkey 菜单将域名添加到白名单。",
        "installUserscriptStep3Title": "开始使用",
        "navFeatures": "功能特性",
        "navHome": "首页",
        "navInstall": "安装指南",
        "navVersions": "版本选择",
        "privacyBackHome": "返回首页",
        "privacyChangesDesc": "我们可能会不时更新此隐私政策。更新内容将发布在本页面。",
        "privacyChangesTitle": "政策更新",
        "privacyContactDesc": "如有关于此隐私政策的问题，请访问：",
        "privacyContactTitle": "联系我们",
        "privacyDataCollectionDesc": "Open In New Tab 不会收集、存储或向外部服务器传输任何个人数据。",
        "privacyDataCollectionTitle": "数据收集",
        "privacyLastUpdated": "最后更新：",
        "privacyLastUpdatedDate": "2026年8月24日",
        "privacyPermActiveTab": "用于检测当前标签页的域名，实现快速添加功能",
        "privacyPermHost": "匹配 *://*/*，用于加载静态内容脚本。脚本会在匹配的页面加载，但仅在白名单域名上修改链接和拦截点击。",
        "privacyPermStorage": "用于通过 chrome.storage.sync 保存上述五个字段",
        "privacyPermissionsTitle": "权限说明",
        "privacyPolicyTitle": "Open In New Tab 隐私政策",
        "privacySyncStorageDesc1": "扩展使用 Chrome 同步存储（chrome.storage.sync）保存以下五个字段：",
        "privacySyncStorageDesc2": "这些数据保存在 Chrome 存储中。登录 Chrome 后，Chrome 可能会在您登录的浏览器之间同步这些数据。我们无法访问这些数据。",
        "privacySyncStorageItem1": "userWhitelist — 您的白名单域名",
        "privacySyncStorageItem2": "openInBackground — 是否在后台打开新标签页",
        "privacySyncStorageItem3": "userTheme — 您的主题偏好（亮色、暗色或自动）",
        "privacySyncStorageItem4": "userLanguage — 您的语言偏好",
        "privacySyncStorageItem5": "updateNoticeEnabled — 更新扩展后是否显示更新说明",
        "privacySyncStorageTitle": "Chrome 同步存储",
        "privacyThirdPartyDesc": "本扩展不使用任何第三方服务、分析工具或跟踪工具。",
        "privacyThirdPartyTitle": "第三方服务",
        "screenshotCaptionDark": "Chrome 扩展 - 深色模式",
        "screenshotCaptionLight": "Chrome 扩展 - 浅色模式",
        "screenshotCaptionUserscript": "用户脚本 - 模态界面",
        "screenshotDarkMode": "深色模式已支持",
        "screenshotExtensionPopup": "扩展弹窗",
        "screenshotModalInterface": "用户脚本模态界面",
        "screenshotQuickAdd": "快速添加当前域名",
        "screenshotWhitelistManager": "白名单管理器",
        "screenshotsSubtitle": "支持深色模式的现代化 UI",
        "screenshotsTitle": "精美界面",
        "tabExtension": "扩展程序",
        "tabUserscript": "用户脚本",
        "versionExtensionBestFor": "最适合：",
        "versionExtensionBestForText": "生产使用、普通用户、Web Store 分发",
        "versionExtensionDesc": "原生 Chrome 扩展，具有更好的性能和无缝的浏览器集成。",
        "versionExtensionFeature1": "现代化弹窗界面",
        "versionExtensionFeature2": "快速添加当前域名",
        "versionExtensionFeature3": "chrome.storage 同步",
        "versionExtensionFeature4": "自动更新（应用商店）",
        "versionExtensionFeature5": "更好的性能",
        "versionExtensionFeatures": "功能特性：",
        "versionExtensionTitle": "Chrome 扩展",
        "versionUserscriptBestFor": "最适合：",
        "versionUserscriptBestForText": "开发者、高级用户、快速测试",
        "versionUserscriptDesc": "非常适合快速测试、开发或偏好使用 Tampermonkey/Greasemonkey 的用户。",
        "versionUserscriptFeature1": "基于菜单的管理",
        "versionUserscriptFeature2": "GM_* 存储 API",
        "versionUserscriptFeature3": "模态界面",
        "versionUserscriptFeature4": "跨浏览器支持",
        "versionUserscriptFeature5": "易于自定义",
        "versionUserscriptFeatures": "功能特性：",
        "versionUserscriptTitle": "用户脚本版本",
        "versionsSubtitle": "两种实现方式，同样强大的功能",
        "versionsTitle": "选择你的版本"
    },
    "zh-TW": {
        "badgeDarkMode": "深色模式",
        "badgeI18n": "國際化支援",
        "badgeLightweight": "輕量級",
        "badgeRecommended": "推薦",
        "badgeSecure": "安全可靠",
        "btnCopied": "已複製！",
        "btnCopyFailed": "複製失敗",
        "btnCopyLink": "複製連結",
        "btnGetStarted": "立即開始",
        "btnInstallExtension": "安裝擴充功能 →",
        "btnInstallNow": "立即安裝 →",
        "btnInstallUserscript": "安裝使用者腳本 →",
        "btnViewDocs": "查看文件",
        "btnViewGithub": "查看倉庫",
        "comparisonDarkMode": "深色模式",
        "comparisonDistGithub": "GitHub",
        "comparisonDistWebStore": "Chrome 線上應用程式商店",
        "comparisonDistribution": "發布方式",
        "comparisonExtension": "擴充功能",
        "comparisonFeature": "功能",
        "comparisonI18n": "國際化",
        "comparisonInstallManual": "手動腳本",
        "comparisonInstallOneClick": "一鍵安裝",
        "comparisonInstallation": "安裝方式",
        "comparisonLinkManagement": "連結管理",
        "comparisonTitle": "功能對比",
        "comparisonUIMenu": "選單命令",
        "comparisonUIPopup": "彈出介面",
        "comparisonUIType": "介面類型",
        "comparisonUpdates": "更新",
        "comparisonUpdatesAuto": "自動",
        "comparisonUpdatesManual": "手動",
        "comparisonUserscript": "使用者腳本",
        "comparisonWhitelist": "白名單控制",
        "ctaDesc": "選擇你偏好的版本，立即開始更智慧地管理你的連結。",
        "ctaTitle": "準備好開始了嗎？",
        "featureDarkModeDesc": "自動適配系統深色/淺色模式偏好，並提供平滑過渡動畫。",
        "featureDarkModeTitle": "深色模式",
        "featureDynamicDesc": "使用 MutationObserver 處理現有和動態新增的連結，實現即時更新。",
        "featureDynamicTitle": "動態內容",
        "featureI18nDesc": "依據瀏覽器設定自動偵測語言（English / 簡體中文 / 繁體中文）。",
        "featureI18nTitle": "國際化",
        "featureSecurityDesc": "自動加入 rel=\"noopener noreferrer\" 屬性以防止安全問題。讓你的瀏覽更安全。",
        "featureSecurityTitle": "安全優先",
        "featureStorageDesc": "你的白名單偏好設定會自動儲存並跨裝置同步。",
        "featureStorageTitle": "持久化儲存",
        "featureWhitelistDesc": "僅套用於指定網域，實現更好的控制和效能。由你決定要增強哪些網站。",
        "featureWhitelistTitle": "白名單模式",
        "featuresSubtitle": "智慧連結管理所需的一切功能",
        "featuresTitle": "強大功能",
        "footerCopyright": "© 2025 Open In New Tab. 依 MIT 授權條款發布。",
        "footerDesc": "智慧連結管理與白名單控制。提供擴充功能和使用者腳本兩個版本。",
        "footerExtensionDocs": "擴充功能文件",
        "footerGithubRepo": "GitHub 倉庫",
        "footerLicense": "MIT 授權條款",
        "footerMadeWith": "用 ❤️ 製作 by",
        "footerMainDocs": "主文件",
        "footerPrivacyPolicy": "隱私權政策",
        "footerQuickLinks": "快速連結",
        "footerReleaseVersion": "目前發布版本 v{version}",
        "footerReportIssues": "回報問題",
        "footerResources": "資源",
        "footerTitle": "Open In New Tab",
        "footerUserscriptDocs": "使用者腳本文件",
        "heroSubtitle": "透過智慧白名單控制，強制每個連結在新分頁開啟。",
        "heroSubtitle2": "提供 Chrome 擴充功能和 Tampermonkey 使用者腳本兩個版本。",
        "heroTitle": "智慧連結管理",
        "heroTitleHighlight": "隨心所控",
        "installExtensionNote": "提示：",
        "installExtensionNoteText": "擴充功能現已正式上線 Chrome 線上應用程式商店，推薦使用一鍵安裝。",
        "installExtensionStep1Desc": "前往 Chrome 線上應用程式商店官方頁面。",
        "installExtensionStep1Title": "造訪應用商店",
        "installExtensionStep2Desc": "點擊「加入 Chrome」即可完成一鍵安裝。",
        "installExtensionStep2Title": "加入 Chrome",
        "installExtensionStep3Desc": "點擊瀏覽器右上角的擴充功能圖示即可管理白名單。",
        "installExtensionStep3Title": "開始使用",
        "installExtensionStep4Desc": "",
        "installExtensionStep4Title": "",
        "installTitle": "快速安裝",
        "installUserscriptAlternative": "備選方案：手動安裝",
        "installUserscriptBtnDirect": "直接安裝",
        "installUserscriptBtnGreasyFork": "從 Greasy Fork 安裝",
        "installUserscriptManualDesc": "如果您偏好手動安裝，可以從 GitHub 下載腳本並在 Tampermonkey 中手動安裝。",
        "installUserscriptStep1Desc1": "安裝",
        "installUserscriptStep1Desc2": "瀏覽器擴充功能。",
        "installUserscriptStep1Title": "安裝 Tampermonkey",
        "installUserscriptStep2Desc": "點擊下方安裝按鈕前往 Greasy Fork，一鍵安裝腳本。",
        "installUserscriptStep2Title": "一鍵安裝",
        "installUserscriptStep3Desc": "造訪任意網站，開啟 Tampermonkey 選單將網域加入白名單。",
        "installUserscriptStep3Title": "開始使用",
        "navFeatures": "功能特性",
        "navHome": "首頁",
        "navInstall": "安裝指南",
        "navVersions": "版本選擇",
        "privacyBackHome": "返回首頁",
        "privacyChangesDesc": "我們可能會不時更新此隱私權政策。更新內容將發布在本頁面。",
        "privacyChangesTitle": "政策更新",
        "privacyContactDesc": "如有關於此隱私權政策的問題，請造訪：",
        "privacyContactTitle": "聯絡我們",
        "privacyDataCollectionDesc": "Open In New Tab 不會收集、儲存或向外部伺服器傳輸任何個人資料。",
        "privacyDataCollectionTitle": "資料收集",
        "privacyLastUpdated": "最後更新：",
        "privacyLastUpdatedDate": "2026年8月24日",
        "privacyPermActiveTab": "用於偵測目前分頁的網域，實現快速加入功能",
        "privacyPermHost": "符合 *://*/*，用於載入靜態內容腳本。腳本會在符合的頁面載入，但僅在白名單網域上修改連結和攔截點擊。",
        "privacyPermStorage": "用於透過 chrome.storage.sync 儲存上述五個欄位",
        "privacyPermissionsTitle": "權限說明",
        "privacyPolicyTitle": "Open In New Tab 隱私權政策",
        "privacySyncStorageDesc1": "擴充功能使用 Chrome 同步儲存（chrome.storage.sync）儲存以下五個欄位：",
        "privacySyncStorageDesc2": "這些資料會保存在 Chrome 儲存中。登入 Chrome 後，Chrome 可能會在您登入的瀏覽器之間同步這些資料。我們無法存取這些資料。",
        "privacySyncStorageItem1": "userWhitelist — 您的白名單網域",
        "privacySyncStorageItem2": "openInBackground — 是否在背景開啟新分頁",
        "privacySyncStorageItem3": "userTheme — 您的主題偏好（亮色、暗色或自動）",
        "privacySyncStorageItem4": "userLanguage — 您的語言偏好",
        "privacySyncStorageItem5": "updateNoticeEnabled — 更新擴充功能後是否顯示更新說明",
        "privacySyncStorageTitle": "Chrome 同步儲存",
        "privacyThirdPartyDesc": "本擴充功能不使用任何第三方服務、分析工具或追蹤工具。",
        "privacyThirdPartyTitle": "第三方服務",
        "screenshotCaptionDark": "Chrome 擴充功能 - 深色模式",
        "screenshotCaptionLight": "Chrome 擴充功能 - 淺色模式",
        "screenshotCaptionUserscript": "使用者腳本 - 浮動介面",
        "screenshotDarkMode": "深色模式已支援",
        "screenshotExtensionPopup": "擴充功能彈窗",
        "screenshotModalInterface": "使用者腳本浮動介面",
        "screenshotQuickAdd": "快速加入目前網域",
        "screenshotWhitelistManager": "白名單管理器",
        "screenshotsSubtitle": "支援深色模式的現代化 UI",
        "screenshotsTitle": "精美介面",
        "tabExtension": "擴充功能",
        "tabUserscript": "使用者腳本",
        "versionExtensionBestFor": "最適合：",
        "versionExtensionBestForText": "正式使用、一般使用者、Web Store 發布",
        "versionExtensionDesc": "原生 Chrome 擴充功能，具有更好的效能和無縫的瀏覽器整合。",
        "versionExtensionFeature1": "現代化彈出介面",
        "versionExtensionFeature2": "快速加入目前網域",
        "versionExtensionFeature3": "chrome.storage 同步",
        "versionExtensionFeature4": "自動更新（應用商店）",
        "versionExtensionFeature5": "更好的效能",
        "versionExtensionFeatures": "功能特性：",
        "versionExtensionTitle": "Chrome 擴充功能",
        "versionUserscriptBestFor": "最適合：",
        "versionUserscriptBestForText": "開發者、進階使用者、快速測試",
        "versionUserscriptDesc": "非常適合快速測試、開發或偏好使用 Tampermonkey/Greasemonkey 的使用者。",
        "versionUserscriptFeature1": "基於選單的管理",
        "versionUserscriptFeature2": "GM_* 儲存 API",
        "versionUserscriptFeature3": "浮動介面",
        "versionUserscriptFeature4": "跨瀏覽器支援",
        "versionUserscriptFeature5": "易於自訂",
        "versionUserscriptFeatures": "功能特性：",
        "versionUserscriptTitle": "使用者腳本版本",
        "versionsSubtitle": "兩種實作方式，同樣強大的功能",
        "versionsTitle": "選擇你的版本"
    }
};

;(function () {
    "use strict"
    var i18n = createI18n(I18nLocales)
    window.i18n = i18n
    // Back-compat: script.js reads translations[lang][key] directly.
    window.translations = I18nLocales
})()
